%% Plotting Stuff for all Plots
function Plot_Function(x, y, P)
    
    Font_Name   = 'Arial';
    Font_Weight = 'bold';

    set(gcf, ...
        'position', [1000, 10, 2*400, 2*300], ...
        'Color',    'white')

    plot(x, y, ...
        'Color',      P.Color, ...
        'LineStyle',  'none', ...
        'MarkerSize', P.MarkerSize, ...
        'Marker',     '.')
    
    % Set Default Tick Size
    if isfield(P, 'x_TSize') == 0
        P.x_TSize = 8;
    end

    set(gca, ...
        'FontName',   Font_Name, ...
        'FontWeight', Font_Weight, ...
        'FontSize',   P.x_TSize, ...
        'xGrid','On', ...
        'yGrid','On', ...
        'xLim',  P.x_Domain, ...
        'yLim',  P.y_Domain, ... 
        'xTick', P.x_Domain(1): P.x_Tick_I: P.x_Domain(2), ...
        'yTick', P.y_Domain(1): P.y_Tick_I: P.y_Domain(2))
    
    % Set Default Label Font Size
    if isfield(P, 'x_FSize') == 0
        P.x_FSize = 12;
        P.y_FSize = 12;

    end

    if isfield(P, 'Title_FSize') == 0
        P.Title_FSize = 16;
    end

    xlabel(P.x_Label, ...
        'FontName',   Font_Name, ...
        'FontWeight', Font_Weight, ...
        'FontSize',   P.x_FSize)
    
    title(P.Title, ...
        'FontName',   Font_Name, ...
        'FontWeight', Font_Weight, ...
        'FontSize',   P.Title_FSize)

    ylabel(P.y_Label, ...
        'FontName',   Font_Name, ...
        'FontWeight', Font_Weight, ...
        'FontSize',   P.y_FSize)

end
