function PlotVelocity(S,C)

    Window = figure( ...
        'Color','w', ...
        'Name','Velocity Analysis', ...
        'NumberTitle','Off');
    % []Opens a new window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    Titles = 'Velocity';
    % []Axes titles.

    YLabels = 'Velocity (km/s)';
    % []Axes subplot y-axis labels.

    Xtick = 50;

    Ytick = 1;
   

    Xmax = ceil(max(S.t/Xtick))*Xtick;

    Ymax = ceil(max(S.v/Ytick))*Ytick;
   
    YLimits = [0, Ymax];
    % []Axes subplot y-axis limits.

    Axes = axes(...
        'FontName','Times', ...
        'FontSize',8, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'XLim',[0,Xmax], ...
        'YLim',YLimits, ...
        'XTick',0:Xtick:Xmax, ...
        'YTick',0:Ytick:Ymax);
    % []Adds an axes to the specified window and adjusts its properties.

    title( ...
        Titles, ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a title to the specified axes and adjusts its properties.

    xlabel( ... 
        'Time (s)', ...
        'FontSize',12, ...
        'Parent',Axes);
    % []Adds a label to the specified x-axis and adjusts its properties.

    ylabel( ...
        YLabels, ...
        'FontSize',12, ...
        'Parent',Axes);
    % []Adds a label to the specified y-axis and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    plot(S.t,S.v, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Adds a plot to the specified axes and adjusts its properties.

end
%===================================================================================================